### PR TITLE
Automation tools, virtualization, etc

### LINKED ISSUE #2: Install - Start - Close the DS Server
A script to Install the server like a dependencie, and start/restart the DS on sails lift.

### PR DESCRIPTION
**Pull request by TylerBre**
fixes #2

### CODE REVIEW

**Comment by TylerBre** [comment]
The README was hard to resolve conflicts on, it's probably a little messed up. Wouldn't mind re-writing it if you want.

**Comment by JcPires** [comment]
Is it that you can change the readme so that it is as clear as possible , I leave you the option to resume from scratch if needed . Could you also comment on the official topic:

http://forum.projectcarsgame.com/showthread.php?33757-Project-Cars-Dedicated-Server-Live-App&p=1037455&viewfull=1#post1037455

again thank you

**Comment by JcPires** [comment]
Impossible to get it work ! I was give a try on my local windows computer, and on my ds also.

On my DS Debian x64:
```
npm WARN cannot run in wd project-cars-ds-webapp@0.0.5 ./scripts/install_steamcmd.sh && ./scripts/install_pcars.sh (wd=/home/live)
render-mustache@0.0.0 ../node_modules/render-mustache
└── mustache@0.7.2
```

On my Windows: 

```
vagrant@packer-virtualbox-iso-1436373933:/vagrant$ npm install
|
> project-cars-ds-webapp@0.0.5 install /vagrant
> ./scripts/install_steamcmd.sh && ./scripts/install_pcars.sh

--2015-07-09 11:19:54--  https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
Resolving steamcdn-a.akamaihd.net (steamcdn-a.akamaihd.net)... 88.221.83.72, 88.221.83.74, 88.221.83.67, ...
Connecting to steamcdn-a.akamaihd.net (steamcdn-a.akamaihd.net)|88.221.83.72|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3170982 (3.0M) [application/octet-stream]
Saving to: ‘/vagrant/steamcmd/steamcmd.tar.gz’

100%[===========================================================================>] 3,170,982   1.51MB/s   in 2.0s

2015-07-09 11:19:57 (1.51 MB/s) - ‘/vagrant/steamcmd/steamcmd.tar.gz’ saved [3170982/3170982]

linux32/
linux32/libstdc++.so.6
linux32/steamcmd
steamcmd.sh
steam.sh
successfully installed steamcmd
Redirecting stderr to '/home/vagrant/Steam/logs/stderr.txt'
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
[  0%] Checking for available update...
[  0%] Downloading update (0 of 10,169 KB)...
[  0%] Downloading update (81 of 10,169 KB)...
[  0%] Downloading update (394 of 10,169 KB)...
[  3%] Downloading update (746 of 10,169 KB)...
[  7%] Downloading update (1,205 of 10,169 KB)...
[ 11%] Downloading update (1,558 of 10,169 KB)...
[ 15%] Downloading update (1,981 of 10,169 KB)...
[ 19%] Downloading update (2,387 of 10,169 KB)...
[ 23%] Downloading update (2,663 of 10,169 KB)...
[ 26%] Downloading update (2,855 of 10,169 KB)...
[ 28%] Downloading update (3,088 of 10,169 KB)...
[ 30%] Downloading update (3,347 of 10,169 KB)...
[ 32%] Downloading update (3,618 of 10,169 KB)...
[ 35%] Downloading update (3,928 of 10,169 KB)...
[ 38%] Downloading update (4,067 of 10,169 KB)...
[ 39%] Downloading update (4,228 of 10,169 KB)...
[ 41%] Downloading update (4,387 of 10,169 KB)...
[ 43%] Downloading update (4,516 of 10,169 KB)...
[ 44%] Downloading update (4,682 of 10,169 KB)...
[ 46%] Downloading update (4,876 of 10,169 KB)...
[ 47%] Downloading update (5,068 of 10,169 KB)...
[ 49%] Downloading update (5,165 of 10,169 KB)...
[ 50%] Downloading update (5,236 of 10,169 KB)...
[ 51%] Downloading update (5,290 of 10,169 KB)...
[ 52%] Downloading update (5,374 of 10,169 KB)...
[ 52%] Downloading update (5,492 of 10,169 KB)...
[ 54%] Downloading update (5,641 of 10,169 KB)...
[ 55%] Downloading update (5,819 of 10,169 KB)...
[ 57%] Downloading update (6,022 of 10,169 KB)...
[ 59%] Downloading update (6,253 of 10,169 KB)...
[ 61%] Downloading update (6,518 of 10,169 KB)...
[ 64%] Downloading update (6,827 of 10,169 KB)...
[ 67%] Downloading update (6,998 of 10,169 KB)...
[ 68%] Downloading update (7,204 of 10,169 KB)...
[ 70%] Downloading update (7,436 of 10,169 KB)...
[ 73%] Downloading update (7,718 of 10,169 KB)...
[ 75%] Downloading update (8,020 of 10,169 KB)...
[ 78%] Downloading update (8,351 of 10,169 KB)...
[ 82%] Downloading update (8,748 of 10,169 KB)...
[ 86%] Downloading update (9,139 of 10,169 KB)...
[ 89%] Downloading update (9,541 of 10,169 KB)...
[ 93%] Downloading update (9,941 of 10,169 KB)...
[ 97%] Downloading update (10,169 of 10,169 KB)...
[100%] Download Complete.
[----] Applying update...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Installing update...
[----] Installing update...
[----] Failed to apply update, reverting...
[----] Verifying installation...
[  0%] Downloading Update...
[  0%] Checking for available update...
[  0%] Download Complete.
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Installing update...
[----] Installing update...
[----] Failed to apply update, reverting...
[----] !!! Fatal Error: Failed to load libsteam.so
cp: target ‘/vagrant/steamcmd/pcars_ds/lib32/’ is not a directory
cp: cannot stat ‘/vagrant/steamcmd/linux32/steamerrorreporter’: No such file or directory
successfully installed pcars dedicated server
render-mustache@0.0.0 node_modules/render-mustache
└── mustache@0.7.2
```

**Comment by TylerBre** [comment]
For your Debian box, try installing the software in this script 

https://github.com/TylerBre/Project-Cars-DS-LiveApp/blob/master/packer/scripts/install_server_software.sh

You can just run that script, just make sure you're the root user.

For the windows one, I'll have to test it

**Comment by TylerBre** [comment]
Regardless, it's probably something small that I missed

**Comment by JcPires** [comment]
Thanks i will try it.

**Comment by TylerBre** [comment]
@JcPires steam isn't installing because it doesn't like to be outside of the current user's home directory

https://github.com/ValveSoftware/steam-for-linux/issues/1981

This is strage, because I'm only getting this error when running the vm on windows. I'll try and figure out a workaround.

And as far as your other issue, just make sure your system is updated with that software and I think it should work

**Comment by TylerBre** [comment]
@JcPires On your debian box, this looks like a permissions issue. 

check out this thread: 
https://github.com/npm/npm/issues/3497#issuecomment-18836246

**Pull request merged**
